# Generated by Django 2.2.2 on 2019-07-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='body',
        ),
    ]
