# Generated by Django 2.2.2 on 2019-07-28 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_author_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='body',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Thông Tin Thêm'),
            preserve_default=False,
        ),
    ]
