# Generated by Django 2.2.2 on 2019-07-29 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_author_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love', models.IntegerField(default=0)),
                ('shocked', models.IntegerField(default=0)),
                ('angry', models.IntegerField(default=0)),
                ('crying', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'React_Post',
                'verbose_name_plural': 'React_Posts',
            },
        ),
    ]
