# Generated by Django 2.2.2 on 2019-07-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_reaction_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='Nội Dung')),
                ('button', models.CharField(choices=[('Download', (('btn blue-gradient btn-primary btn-md', 'class'), ('fas fa-download', 'icon'))), ('Đường Dẫn', (('btn blue-gradient btn-primary btn-md', 'class'), ('fas fa-location-arrow', 'icon')))], max_length=200, verbose_name='Button')),
                ('link', models.CharField(max_length=200, verbose_name='Đường Dẫn')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
            options={
                'verbose_name': 'Button_Post',
                'verbose_name_plural': 'Button_Posts',
            },
        ),
    ]
