# Generated by Django 2.2.2 on 2019-07-30 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_button_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button_post',
            options={'verbose_name': 'Button', 'verbose_name_plural': 'Button'},
        ),
        migrations.AlterField(
            model_name='button_post',
            name='button',
            field=models.CharField(choices=[('DW', 'Downloads'), ('LK', 'Links')], max_length=200, verbose_name='Button'),
        ),
        migrations.AlterField(
            model_name='button_post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button', to='posts.Post'),
        ),
    ]
