# Generated by Django 2.2.2 on 2019-08-01 13:25

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190731_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=500, verbose_name='Avaatar'),
        ),
    ]
